export default async function getBrandVariables(domain: string): Promise<BrandVariables> {
  const res = await fetch(`https://${domain}/api/v1/brand_variables?no_verifiers=1`);
  const data = await res.json();
  return data;
}

export type BrandVariables = {
  "ic-brand-primary-darkened-5": string;
  "ic-brand-primary-darkened-10": string;
  "ic-brand-primary-darkened-15": string;
  "ic-brand-primary-lightened-5": string;
  "ic-brand-primary-lightened-10": string;
  "ic-brand-primary-lightened-15": string;
  "ic-brand-button--primary-bgd-darkened-5": string;
  "ic-brand-button--primary-bgd-darkened-15": string;
  "ic-brand-button--secondary-bgd-darkened-5": string;
  "ic-brand-button--secondary-bgd-darkened-15": string;
  "ic-brand-font-color-dark-lightened-15": string;
  "ic-brand-font-color-dark-lightened-28": string;
  "ic-link-color-darkened-10": string;
  "ic-link-color-lightened-10": string;
  "ic-brand-primary": string;
  "ic-brand-font-color-dark": string;
  "ic-link-color": string;
  "ic-brand-button--primary-bgd": string;
  "ic-brand-button--primary-text": string;
  "ic-brand-button--secondary-bgd": string;
  "ic-brand-button--secondary-text": string;
  "ic-brand-global-nav-bgd": string;
  "ic-brand-global-nav-ic-icon-svg-fill": string;
  "ic-brand-global-nav-ic-icon-svg-fill--active": string;
  "ic-brand-global-nav-menu-item__text-color": string;
  "ic-brand-global-nav-menu-item__text-color--active": string;
  "ic-brand-global-nav-avatar-border": string;
  "ic-brand-global-nav-menu-item__badge-bgd": string;
  "ic-brand-global-nav-menu-item__badge-bgd--active": string;
  "ic-brand-global-nav-menu-item__badge-text": string;
  "ic-brand-global-nav-menu-item__badge-text--active": string;
  "ic-brand-global-nav-logo-bgd": string;
  "ic-brand-header-image": string;
  "ic-brand-mobile-global-nav-logo": string;
  "ic-brand-watermark": string;
  "ic-brand-watermark-opacity": string;
  "ic-brand-favicon": string;
  "ic-brand-apple-touch-icon": string;
  "ic-brand-msapplication-tile-color": string;
  "ic-brand-msapplication-tile-square": string;
  "ic-brand-msapplication-tile-wide": string;
  "ic-brand-right-sidebar-logo": string;
  "ic-brand-Login-body-bgd-color": string;
  "ic-brand-Login-body-bgd-image": string;
  "ic-brand-Login-body-bgd-shadow-color": string;
  "ic-brand-Login-logo": string;
  "ic-brand-Login-Content-bgd-color": string;
  "ic-brand-Login-Content-border-color": string;
  "ic-brand-Login-Content-inner-bgd": string;
  "ic-brand-Login-Content-inner-border": string;
  "ic-brand-Login-Content-inner-body-bgd": string;
  "ic-brand-Login-Content-inner-body-border": string;
  "ic-brand-Login-Content-label-text-color": string;
  "ic-brand-Login-Content-password-text-color": string;
  "ic-brand-Login-footer-link-color": string;
  "ic-brand-Login-footer-link-color-hover": string;
  "ic-brand-Login-instructure-logo": string;
};
